name: firebasae_push_notification_2
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  equatable: any
  flutter_bloc: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  google_sign_in: any
  permission_handler: any
  gap: any
  json_annotation: any
  firebase_messaging: any
  googleapis_auth: any
  http: any
  app_settings: any
  flutter_local_notifications: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0
  json_serializable:
  build_runner:




flutter:

  
  
  
  uses-material-design: true

  assets:
    - asset/notification.json

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
